### ISSUE TITLE
!!! Consider renaming of the phred alphabet

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#249]
### Description

Discuss and re-evaluate the naming schemes of the quality alphabets to make them either consistent with the other alphabets or consistent with the technology they represent.

The current naming scheme used to select the proper phred score is difficult to understand, because the meaning of the numbers differentiates from the meaning of the other alphabets, which is the size of the alphabet. According to this [article](https://en.wikipedia.org/wiki/FASTQ_format#Quality) following alphabets could be derived:
 - phred94: (Sanger format and used by current Illumina sequencers) rank: 0..93 ASCII 33..126 (`seqan3::phred63` and `seqan3::phred42`)
 - phred68: (Illumina 1.0 until Illumina 1.3) rank: -5..62 ASCII 59..126 (`seqan3::phred68legacy`)
 - phred63: (Illumina 1.3 until Illumina 1.8) rank: 0..62 ASCII 64..126 (`seqan3::phred68legacy` is a superset of this)
 - phred63+: (Illumina 1.5 until Illumina 1.8) rank: 0..2 have different meaning

Then we added a phred42, which is not represented by any of the above quality ranges but merely serves as the smallest size that can be stored together with a dna5 in an alphabet tuple using only one byte.
This makes sense, as the Illumina sequencers usually do not provide qualities higher than 40, but assemblies etc. could.

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>

**Comment by smehringer** [comment]
Current state (Taken from Hannes' Diss):

![image](https://user-images.githubusercontent.com/7955878/100578805-4f0ab980-32e3-11eb-9436-d79ff4963a42.png)

### Summary 

**The most commonly used quality score notation is the original Sanger phred notation which is also used by Illumina since version 1.8** of their pipeline 23 and formats like SAM (H. Li et al., 2009). Since phred score scores are ≥ 0 (see definition at beginning of this section), the phred representation can be stored internally and is identical to the rank. The character offset for this notation is 33, i.e. the character range begins at the character '!' .

Originally the Sanger phred notation was meant to hold quality values from 0 to 93, but any sequencing technology since the Illumina 1.3 pipeline only produced values up to 41 (P. J. Cocket al., 2010). Higher values were reserved for confidence achievable through post-processing; typically values only up to 62 are used. **`seqan3::phred42` and `seqan3::phred63` both implement this notation, one with a maximum representable quality value of 41 and the other with 62**. Both accept
quality values outside their range which will result in a conversion to the respective maximum (or minimum for negative values). As with other alphabets, the main difference is the size of the alphabet.

**Before version 1.8**, versions 1.3 and 1.5 of the Illumina pipeline were popular. Their quality **notation was also phred-based but the character offset was 64 (character '@' ) instead of 33 (character '!' )**. A type for these notations is provided for backwards-compatibility: the `seqan3::phred68legacy` alphabet. However, a second type with a smaller value range is not provided since these formats are rarely used today.

### Motivation of the chosen alphabet sizes

Quality alphabets can be combined with nucleotide alphabets via `seqan3::qualified`, a derived type of `seqan3::alphabet_tuple_base`. The main advantage is compression, the following combinations all still fit into a single byte:
* `seqan3::qualified<seqan3::dna4, seqan3::phred42>` (alphabet size 168)
* `seqan3::qualified<seqan3::dna4, seqan3::phred63>` (alphabet size 252)
* `seqan3::qualified<seqan3::dna5, seqan3::phred42>` (alphabet size 210)

A vector over such a combined alphabet can thus save 50% of storage space compared to two separate vectors (of course the same combinations with RNA alphabets are possible).

**Comment by smehringer** [comment]
### Resolution 2020-11-30

We concluded the following things:
  * We will keep the current naming of the quality alphabet (phred42/63/94) 
  * We need to describe the implemented phred scores (Sanger/Solexa formats) more clearly in the documentation (see [follow up issue](https://github.com/seqan/product_backlog/issues/266))
  * We want a phred94 alphabet that can represent the full range of Sanger encoded phred scores. [see follow up issue](https://github.com/seqan/product_backlog/issues/267) 
  * The phred94 alphabet should be the default when reading quality scores

**Comment by smehringer** [comment]
Follow up issues are created
