### ISSUE TITLE
SeqAn Developer Meeting 2021

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#299]
### Description 

* [x] Find date: 28.-30.06.2021 (3 days)
* [x] Write save-the-date E-Mail
* [x] Invite People (Knut will do this, 2021-06-15)
* [ ] Announce via Website
* [x] Announce via de.NBI Website (2021-06-07 E-Mail sent to Daniel; https://www.denbi.de/planned-training-course-2021/1166-seqan-developer-meeting-2021)
* [x] Announce via E-Mail
* [x] Plan Schedule
* [x] Book rooms 006 (Knut will do this)
* [x] Survey Link: https://de.surveymonkey.com/r/denbi-course?sc=cibi&id=000311

**Comment by marehr** [comment]
2019: https://www.denbi.de/training-archive-sorted-according-by-date/2019/541-seqan-developer-meeting-2019
2021: https://www.denbi.de/planned-training-course-2021/1166-seqan-developer-meeting-2021

de.NBI Training Event Description

### Title
SeqAn Developer Meeting 2021 

### Educators

Marcel Ehrhardt, Enrico Seiler

### Date

28. \- 30.06.2021

### Location

Online

### Contents

The SeqAn project will hold its SeqAn3 developer meeting and an ELIXIR / de.NBI / CIBI workshop
online at the end of June (28th to 30th).

Goal of the meeting is to kickstart new projects with our collaborators from RKI, MPI, Italy, etc. and for the SeqAn core team to plan the direction of the next SeqAn3 release.

Additionally, to working on the release of SeqAn3, the SeqAn team will offer a workshop as part of ELIXIR Germany that includes trainings and hands-on sessions so that our project partners and interested guests are the first to learn how to use our new software and related programming techniques. Those parties will be able to come to the meeting with their current research problems or existing applications, and we will do our best to port these or develop new working proto-types with them on-site. Furthermore, the meeting  provides a unique opportunity for those parties to present their research and  formulate expectations they have of a modern Bionformatics library/framework  and thereby influence the future development of SeqAn in a way that benefits their work in the long run.

### Learning goals

- Software engineering and App development with SeqAn
- High-performance computing using SeqAn and the STL
- Modern C++ features like Concepts, Ranges, and many more

### Prerequisites

This tutorial is mostly suited for computational biologist and bioinformaticians with research focus on sequence analysis (e.g., genomics, metagenomics, assembly, read alignment, variant detection, etc.) Attendees must have an intermediate level of programming skills and a strong interest in C++ as well as a fundamental background in the SeqAn3 software library. Attendees must bring their own laptop. Software for the tutorial should be installed beforehand, but we will also dedicate some extra time for setting up the workstations. The following systems/software is required:

- MacOS (g++-7 or higher) or Linux or BSD (g++-7 or higher)
- Git
- Cmake-3.8 or higher

### Keywords

SeqAn3, Sequence Analysis, modern C++

### Tools

SeqAn3: https://www.denbi.de/services/370-seqan-a-c-library-for-the-analysis-of-sequences

### Registration

The number of participants is limited to 20. To register please write an email to the contact person below.

### Contact

seqan-dev@lists.fu-berlin.de

**Comment by marehr** [comment]
(maybe?) Participants: 

Invitations: Gianvito (Italy), Vitor (HPI), Tobias (HPI), Christopher Pockrandt (Salzberg), Remy Schwab (UMD / MPI), Birte Kehr + Group (Regensburg), Chris Bielow (BSC), Sandro (BSC), Max von Kleist (RKI), Hossein (iGenVar, MPI, Martin Vingron), Monika? (iGenVar, MPI, Martin Vingron), Sara Hetzel (Lambda, MPI, Meissner)

### Schedule:

|   | 28th June (Monday) | 29th | 30th |
| --- | --- | --- | --- |
| 09:00 - 09:30 | Welcome Presentation (Knut) | CiBi/Elixier State of Things (Michael Crusoe) | Break-Out Groups |
| 09:30 - 10:00 | Short Project Presentation (Target: 10 min + 5 min Discussion) (1 / 2) | External Presentation (Maybe CiBi; Marcel + Simon / Lambda Feature-Complete ) | Break-Out Groups |
| 10:00 - 10:30 | Short Project Presentation (Target: 10 min + 5 min Discussion) (3 / 4) | SFB Fonda Plans (Evelin, Somayeh) | Break-Out Groups |
| 10:30 - 11:00 | Coffee-Break | Coffee-Break | Coffee-Break |
| 11:00 - 11:30 | Short Project Presentation (Target: 10 min + 5 min Discussion) (5 / 6) | iGenVar 1 | Break-Out Groups (Parallelisation Marcel) |
| 11:30 - 12:00 | Short Project Presentation (Target: 10 min + 5 min Discussion) (7 / 8) | iGenVar 2 | Break-Out Groups (SeqAn Whishlist) |
| 12:00 - 13:30 | Lunch | Lunch | 12:00 (Rene's Mail); Lunch |
| 13:30 - 16:00 | Backend Archive-Index and Live-Dream | Frontend Archive-Index Session 1 / Frontend Live-Dream Session 2 | Closing Remarks (SeqAn Team meets after this.) |


### Topics:

* Short project presentations
  * Tobias: Developments in Live-Dream
  * Vitor: Developments in ganon2
  * Rene: Integrating the JST in the DREAM-Framework
  * Enrico: The HIBF
  * Marcel: Better parallelisation strategy for DREAM-framework
  * Lydia: Developments in iGenVar 
  * Mitra: quantitative IBF
  * Simon: ???
  * One Open Slot
* Discussion-Rounds:
  * Future of SeqAn: smaller modules?
* Project-Discussions:
  * What are the next steps in the projects?
  * iGenVar, Live-Dream, Archive-Index
* SeqAn3 wish list :)

### Toolings:
* [ ] ~~Zoom?~~ / WebEx
* [ ] Online Whiteboard?
  * https://draw.chat
* [ ] iPads: Knut asks if they are available
  * https://www.goodnotes.com/
* [ ] At the location?

**Comment by rrahn** [comment]
# Notes from the meeting

### HIBF/DREAM Index Backend

* all instances of IBF should be replaced with HIBF
* Adapt the query interface such that it can be used interchangeably with IBF.
* Put working HIBF search into seqan/hibf repository
* People can then use this repository for the search
* Keep the HIBF construction into chopper as external tool at the moment.
* After clarifying the interface for the construction we can start putting it into the hibf repository, such that external people can then update their tools to internally build the HIBF if desired. Until then they can use chopper for their experiments.
* Some thoughts about additional interfaces for the HIBF/DREAM Index are presented in: https://gist.github.com/rrahn/3ba29fefdb913fcbd1303f0d086422b4
* Investigate how the FPR in the merged bins could be increased in order to make the lower-level IBFs smaller and thus more efficient.

### DREAM Index Frontend
* Look into https://gitlab.ub.uni-bielefeld.de/gi/socks
* Look into https://www.biorxiv.org/content/10.1101/2021.02.16.431451v1
* Start with a simple framework:
  * Index the RefSeq with roughly ~1.7 TB
  * Offer a simple gui/web-interface where people can filter the files which contain the given queries
  * Output could be list of accession numbers
  * Then provide the corresponding interactions with the server execution.
* Further ideas:
  * BLAST Search using Lambda on filtered files
  * guided sequence analysis (search/mapping, etc). So the user can configure after initial identification of items: files, organisms, tissues, etc. which one he wants to analyze more closely with different methods: Lambda, Mapping+Calling, etc.
  * what about privacy concern when uploading sequence data?
  * (email) notification system: Requires database to store the results per job, respective notification service, displaying/downloading results
  * workflow: search for interesting items -> filter/selection of those manually/semi-automatic (could offer some filter options, like all items within a specific threshold, etc.)
* Possible Applications
   *  SRA data mining, e.g. after identification of new species -> scan the SRA to check if this species was already found in previous experiments without knowing
   * trace newly discovered resistant genes: in which country did it occur, how did it spread, etc.
   * hospital surveillance to trace pathogens/bacteria 
* Schedule:
   * Prepare some initial prototype designs for basic application
   * Which tools/infrastructure is required or must be installed on dedicated server
   * Develop prototype for workshop in 2022: invite possible interested groups: RKI, MPI, Charité, HPI, biologists with specific problems we might be able to solve with our strategy

### iGenVar

#### SeqAn related:
* needs faster BAM parsing
* Port VCF-parser to SeqAn3 (merge with input parser from jstmap)
* Compare interval tree with https://github.com/seqan/seqan/blob/master/include/seqan/misc/interval_tree.h
* Needs BAM index 

#### Planned procedure:
* short-term: detect SVs in short reads
* mid-term: detect mostly all types of SVs excluding special cases like nested SVs and detect SNPs and Indels
* long-term: improve the iGenVar tool with adding other mehtods for a higher efficiency and for detecting special case SVs e.g. SVs in repetitive regions

#### Proposed division of tasks:
* Lydia: extend the existing tool to call other SV types and use methods for short and long read input 
* Jörg: include methods of GATK / SNP calling
* Jongkyu: include methods of Vaquita
* Josh: BAM indexing, Vaquita-LR?, sViper?

**Comment by marehr** [comment]
![seqan-library-structure](https://user-images.githubusercontent.com/103778/123983871-7da95980-d9c4-11eb-8f57-61755f801bac.png)

**Comment by marehr** [comment]
Feedback:

* Good overview over what projects are being worked on.
* More moderation:
  * Repeating the question.
  * Sound-Quality was bad, because the Questioner couldn't be heard
* Hybrid-Meetings:
  * Need a good conference microphone; otherwise too much interference
* Mailing-List? / Tailored E-Mail Recipients
  * Extracted from a Registration
  * Too many e-mail recipients
* Sometimes we didn't know which Meeting was important for which Person
