### ISSUE TITLE
Allow to overwrite existing output files.

### ISSUE THREAD

**Issue by joergi-w** [seqan/product_backlog#50]
I have spotted in PR seqan/seqan3#1691 that an already existing output file cannot be overwritten and I herewith request to allow this. 

As an _application user_ and _tester_ I want to run the same command-line several times without bothering to rename my output every time. As a _command line user_ I am generally aware (e.g. from any other unix program) that an output file which exists is going to be overwritten and I am able to shoulder the responsibility for this. As an _application developer_ I want to at least have a choice of enabling overwrite protection or not. 

**Therefore I suggest the following behaviour:** By default we do not enforce the absence of an output file. The application developer has a flag to enable overwrite protection if they think it is crucial for this application. 

And as an optional (nice-to-have) feature: there could be another flag that allows to append output to an existing file (or create if not present), which is useful for merging record-based files like Fasta etc.

### Resolution
  * Pass in a flag to indicate how to open a file for write: Overwrite, append, new
  * Show the requirements for open a file in the help page message.

**Comment by rrahn** [comment]
### Resolution

  * Pass in a flag to indicate how to open a file for write: Overwrite, append, new
  * Show the requirements for open a file in the help page message.

**Comment by marehr** [comment]
2020-08-31 Core Meeting

Discussion result:
```cpp
enum output_file_open_options
{
    open_or_create,
    create_new
};
```
You call this validator like:
```cpp
seqan3::output_file_validator{seqan3::output_file_open_options::open_or_create});
```


----

Open Question: `seqan3::output_file_validator` has a template parameter, can we remove it? If yes, we could make the enum part of the class:

```c++
enum output_file_open_options
{
    open_or_create,
    create_new
};

seqan3::output_file_validator{seqan3::output_file_open_options::open_or_create};

// could be
seqan3::output_file_validator{seqan3::output_file_validator::open_or_create};
```

**Comment by rrahn** [comment]
> Open Question: seqan3::output_file_validator has a template parameter, can we remove it? 

We basically could, if we provide another mechanism to get the valid file formats, e.g. using a dedicated function to extract the formats and also the possible extensions. But that was open for debate how to do it since there are two contradicting feature requests: 1. get the list of extensions including the allowed compression formats and 2. Do not list all extensions with all compression format combinations. I think the latter can be resolved as a feature of the validator, such that it checks the list of extensions and identifies the compression extensions and then itself provides the information in the help as `.fasta{.gz|.bz2} .fa{.gz|.bz2} .embl{.gz|.bz2}` maybe?
